-- Branded message template foundation.
-- Source-only until explicitly reviewed and rolled out.
-- No outbound provider calls, email sending, unsubscribe handling or n8n activation live here.

create table if not exists public.message_templates (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null
    references public.workspaces(id) on delete cascade,
  template_key text not null
    check (
      char_length(template_key) between 3 and 80
      and template_key ~ '^[a-z0-9]+(?:[a-z0-9-]*[a-z0-9])?$'
    ),
  name text not null
    check (char_length(btrim(name)) between 1 and 120),
  channel text not null default 'email'
    check (channel = 'email'),
  purpose text not null default 'follow_up'
    check (purpose in ('follow_up', 're_engagement', 'custom')),
  subject_template text not null
    check (char_length(subject_template) between 1 and 300),
  body_template text not null
    check (char_length(body_template) between 1 and 12000),
  tone text not null default 'friendly'
    check (tone in ('professional', 'friendly', 'warm', 'concise')),
  is_enabled boolean not null default true,
  is_default boolean not null default false,
  version integer not null default 1
    check (version >= 1),
  created_by uuid
    references auth.users(id) on delete set null
    default auth.uid(),
  updated_by uuid
    references auth.users(id) on delete set null
    default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, template_key)
);

comment on table public.message_templates is
  'Workspace-scoped plain-text message templates. Rendering is deterministic and outbound delivery is handled by a separate future layer.';
comment on column public.message_templates.template_key is
  'Stable machine identifier for future automation references. Immutable after insert.';
comment on column public.message_templates.subject_template is
  'Plain-text email subject template. HTML is not accepted by the template editor.';
comment on column public.message_templates.body_template is
  'Plain-text body template. Future outbound HTML must be generated by a controlled renderer, not user-authored HTML.';
comment on column public.message_templates.version is
  'Monotonic revision number incremented by the database whenever an editable template row changes.';

create index if not exists message_templates_workspace_purpose_idx
  on public.message_templates (workspace_id, purpose, is_enabled);

create unique index if not exists message_templates_one_default_per_purpose_idx
  on public.message_templates (workspace_id, channel, purpose)
  where is_default;

alter table public.message_templates enable row level security;

drop policy if exists message_templates_member_read
  on public.message_templates;
create policy message_templates_member_read
on public.message_templates
for select
to authenticated
using (
  (select private.is_workspace_member(message_templates.workspace_id))
);

drop policy if exists message_templates_admin_insert
  on public.message_templates;
create policy message_templates_admin_insert
on public.message_templates
for insert
to authenticated
with check (
  (select private.is_workspace_member(
    message_templates.workspace_id,
    array['owner'::text, 'admin'::text]
  ))
);

drop policy if exists message_templates_admin_update
  on public.message_templates;
create policy message_templates_admin_update
on public.message_templates
for update
to authenticated
using (
  (select private.is_workspace_member(
    message_templates.workspace_id,
    array['owner'::text, 'admin'::text]
  ))
)
with check (
  (select private.is_workspace_member(
    message_templates.workspace_id,
    array['owner'::text, 'admin'::text]
  ))
);

-- Hard delete is intentionally unavailable in v1. Templates can be disabled.
-- This preserves stable automation references until a recovery/history UX exists.
drop policy if exists message_templates_admin_delete
  on public.message_templates;

revoke all on table public.message_templates from anon;
revoke all on table public.message_templates from authenticated;

grant select on table public.message_templates to authenticated;
grant insert (
  workspace_id,
  template_key,
  name,
  channel,
  purpose,
  subject_template,
  body_template,
  tone,
  is_enabled,
  is_default
) on table public.message_templates to authenticated;
grant update (
  template_key,
  name,
  purpose,
  subject_template,
  body_template,
  tone,
  is_enabled,
  is_default
) on table public.message_templates to authenticated;
grant all on table public.message_templates to service_role;

create or replace function private.bump_message_template_revision()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.template_key is distinct from old.template_key then
    raise exception 'message template key is immutable'
      using errcode = '22023';
  end if;

  new.version := old.version + 1;
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

revoke all on function private.bump_message_template_revision() from public;
revoke all on function private.bump_message_template_revision() from anon;
revoke all on function private.bump_message_template_revision() from authenticated;

drop trigger if exists trg_message_templates_revision
  on public.message_templates;
create trigger trg_message_templates_revision
before update on public.message_templates
for each row execute function private.bump_message_template_revision();

insert into public.message_templates (
  workspace_id,
  template_key,
  name,
  purpose,
  subject_template,
  body_template,
  tone,
  is_enabled,
  is_default
)
select
  w.id,
  seed.template_key,
  seed.name,
  seed.purpose,
  seed.subject_template,
  seed.body_template,
  seed.tone,
  true,
  true
from public.workspaces w
cross join (
  values
    (
      'hot-follow-up'::text,
      'Hot lead follow-up'::text,
      'follow_up'::text,
      'Quick follow-up, {{lead.first_name}}'::text,
      E'Hi {{lead.first_name}},\n\nThanks for reaching out to {{workspace.company_name}}. I wanted to follow up while your request is still fresh. Reply here if you would like us to help with the next step.\n\n{{workspace.email_signature}}'::text,
      'friendly'::text
    ),
    (
      'warm-re-engagement'::text,
      'Warm lead re-engagement'::text,
      're_engagement'::text,
      'Still interested, {{lead.first_name}}?'::text,
      E'Hi {{lead.first_name}},\n\nJust checking back in from {{workspace.company_name}}. If this is still something you are considering, reply when the timing is right and our team can pick it back up.\n\n{{workspace.email_signature}}'::text,
      'warm'::text
    )
) as seed(template_key, name, purpose, subject_template, body_template, tone)
on conflict (workspace_id, template_key) do nothing;

create or replace function private.ensure_workspace_message_templates()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.message_templates (
    workspace_id,
    template_key,
    name,
    purpose,
    subject_template,
    body_template,
    tone,
    is_enabled,
    is_default,
    created_by,
    updated_by
  )
  values
    (
      new.id,
      'hot-follow-up',
      'Hot lead follow-up',
      'follow_up',
      'Quick follow-up, {{lead.first_name}}',
      E'Hi {{lead.first_name}},\n\nThanks for reaching out to {{workspace.company_name}}. I wanted to follow up while your request is still fresh. Reply here if you would like us to help with the next step.\n\n{{workspace.email_signature}}',
      'friendly',
      true,
      true,
      new.created_by,
      new.created_by
    ),
    (
      new.id,
      'warm-re-engagement',
      'Warm lead re-engagement',
      're_engagement',
      'Still interested, {{lead.first_name}}?',
      E'Hi {{lead.first_name}},\n\nJust checking back in from {{workspace.company_name}}. If this is still something you are considering, reply when the timing is right and our team can pick it back up.\n\n{{workspace.email_signature}}',
      'warm',
      true,
      true,
      new.created_by,
      new.created_by
    )
  on conflict (workspace_id, template_key) do nothing;

  return new;
end;
$$;

revoke all on function private.ensure_workspace_message_templates() from public;
revoke all on function private.ensure_workspace_message_templates() from anon;
revoke all on function private.ensure_workspace_message_templates() from authenticated;

drop trigger if exists trg_workspaces_ensure_message_templates
  on public.workspaces;
create trigger trg_workspaces_ensure_message_templates
after insert on public.workspaces
for each row execute function private.ensure_workspace_message_templates();
