create table public.ai_memory_documents (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  memory_id uuid references public.ai_memories(id) on delete cascade,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(768),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(memory_id)
);

create index ai_memory_documents_workspace_idx on public.ai_memory_documents(workspace_id, updated_at desc);

alter table public.ai_memory_documents enable row level security;
create policy ai_memory_documents_read on public.ai_memory_documents for select to authenticated using (private.is_workspace_member(workspace_id));
create policy ai_memory_documents_admin_write on public.ai_memory_documents for all to authenticated using (private.is_workspace_member(workspace_id, array['owner','admin'])) with check (private.is_workspace_member(workspace_id, array['owner','admin']));

create trigger trg_ai_memory_documents_updated_at before update on public.ai_memory_documents for each row execute function private.set_updated_at();

create or replace function public.match_ai_memory_documents(
  query_embedding extensions.vector(768),
  match_count int default 8,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
#variable_conflict use_column
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.ai_memory_documents d
  where d.embedding is not null
    and d.metadata @> filter
  order by d.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 50);
end;
$$;

revoke all on function public.match_ai_memory_documents(extensions.vector, int, jsonb) from public;
grant execute on function public.match_ai_memory_documents(extensions.vector, int, jsonb) to service_role;
;
